source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target "BangBangBao" do

	pod 'MBProgressHUD'
	pod 'SDWebImage'
	pod 'MJRefresh'
	pod 'GBVersionTracking'
	pod 'Masonry'
	pod 'Reveal-iOS-SDK', :configurations => ['Debug']
	pod 'YTKKeyValueStore'
	pod 'YTKNetwork'
	pod 'TOWebViewController'
	pod 'IQKeyboardManager'
	pod 'ActionSheetPicker-3.0'
	pod 'JGActionSheet'
	pod 'JDStatusBarNotification'
	pod 'VTAcknowledgementsViewController'
	pod 'YYModel'
	pod 'LBXScan'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'Flurry-iOS-SDK/FlurrySDK'
	pod 'JPFPSStatus'
	pod 'ClusterPrePermissions'
	pod 'APAddressBook'
	pod 'LCUIKit'
	
end